import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="min-h-[60vh]">{children}</div>;
}
